# Spring Boot configuration
spring:
  liquibase:
    enabled: true #Change to true after adding master for Liquibase
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bies-realm
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/idea_db
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8080
